# Generated by Django 4.1.6 on 2023-02-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_status_alter_app_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['pk'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='incidents.status', verbose_name='Статус завки'),
        ),
    ]
